### ISSUE TITLE
[3] stability of display control during aging test (must not stop)

### ISSUE THREAD

**Issue by hirotoshi-uchino-hacarus** [hacarus/progress-management#907]
***In GitLab by @mitsutaka on May 19, 2023, 09:21 GMT+9:***

**Assignees:** mitsutaka

*Migrated from GitLab: https://gitlab.hacarus.com/hacarus/internal/hacarus-check/hacarus-check-robo/progress-management/-/issues/1144*

**Comment by hirotoshi-uchino-hacarus** [comment]
***In GitLab by @mitsutaka on May 19, 2023, 09:21 GMT+9:***

changed due date to May 24, 2023

**Comment by hirotoshi-uchino-hacarus** [comment]
***In GitLab by @mitsutaka on May 19, 2023, 09:22 GMT+9:***

# 5/19 エージング停止

停止時のサーバ側のログ。

```
May 18 08:01:22 robo1-raspi FbiServer.py[341]: Received from client 1g
May 18 08:01:22 robo1-raspi FbiServer.py[341]: Traceback (most recent call last):
May 18 08:01:22 robo1-raspi FbiServer.py[341]:   File "/home/hacarus/HacarusCheckRobo/FbiServer.py", line 70, in <modul>
May 18 08:01:22 robo1-raspi FbiServer.py[341]:     main(srvHost, srvPort)
May 18 08:01:22 robo1-raspi FbiServer.py[341]:   File "/home/hacarus/HacarusCheckRobo/FbiServer.py", line 46, in main
May 18 08:01:22 robo1-raspi FbiServer.py[341]:     recvData = clntSock.recv(1024)
May 18 08:01:22 robo1-raspi FbiServer.py[341]: ConnectionResetError: [Errno 104] Connection reset by peer
May 18 08:01:23 robo1-raspi systemd[1]: FbiServer.service: Main process exited, code=exited, status=1/FAILURE
May 18 08:01:23 robo1-raspi systemd[1]: FbiServer.service: Failed with result 'exit-code'.
May 18 08:01:23 robo1-raspi systemd[1]: FbiServer.service: Consumed 26min 33.324s CPU time.
```

# 対策

https://gitlab.hacarus.com/hacarus/internal/hacarus-check/hacarus-check-robo/progress-management/-/issues/1089　で作成した systemd用設定ファイル `FbiServer.service` にて、 `Restart=always` オプションを追加。  
何かしらの理由でサービスが死んでも、自動的に立ち上がることで対応した。

**Comment by hirotoshi-uchino-hacarus** [comment]
***In GitLab by @jason on May 22, 2023, 10:27 GMT+9:***

marked this issue as related to #1150

**Comment by hirotoshi-uchino-hacarus** [comment]
***In GitLab by @mitsutaka on May 23, 2023, 17:26 GMT+9:***

marked this issue as related to hacarus-check-robo-frontend#205

**Comment by hirotoshi-uchino-hacarus** [comment]
***In GitLab by @jason on May 25, 2023, 10:48 GMT+9:***

removed the relation with #1150

**Comment by hirotoshi-uchino-hacarus** [comment]
***In GitLab by @jason on May 25, 2023, 10:49 GMT+9:***

marked this issue as related to #1163

**Comment by hirotoshi-uchino-hacarus** [comment]
***In GitLab by @mitsutaka on May 25, 2023, 11:19 GMT+9:***

marked this issue as related to #1164

**Comment by hirotoshi-uchino-hacarus** [comment]
***In GitLab by @mitsutaka on May 30, 2023, 09:15 GMT+9:***

# Oops Terminatedと表示されることがある

fbiが異常状態に陥ってる様子だが、fbi自体が死んでいるわけでもない？  
現象発生時に検証を行う。  
[pkill したら発生したと報告](https://stackoverflow.com/questions/24022342/os-kill-leaking-oops-terminated-into-console)があるが、手元でやっても再現しなかった。
